In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Lasso
#pipelines for transforms
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures

In [8]:
x = pd.read_csv('x.csv')
y = x['worldwide_gross']
x = x.drop('worldwide_gross', axis=1)
x_train, x_test, y_train, y_test = train_test_split(x, y)
scaler = StandardScaler()
scaler.fit(x_train)
scaler.mean_

array([3.34335170e+07, 2.00224902e+03, 2.11794254e+00, 1.08373070e+02,
       1.01768073e+04, 4.15540909e+07, 6.45714750e+00, 4.85791863e+07])

In [9]:
scaler.scale_

array([4.14946504e+07, 1.20097082e+01, 6.73857976e-01, 2.25312355e+01,
       1.64207919e+04, 2.31446338e+08, 1.05824799e+00, 6.54528112e+07])

In [10]:
scaler.transform(x_train)

array([[-0.27554195, -0.77012863, -0.39762465, ..., -0.07800552,
        -2.41639722, -0.57878303],
       [ 4.25516256,  0.64539286,  0.34437147, ...,  0.68459026,
         0.22948544,  0.86536464],
       [-0.68523332,  0.14579704, -0.39762465, ..., -0.15793765,
         0.41847705, -0.60795664],
       ...,
       [ 0.03775145, -0.0207349 ,  0.34437147, ..., -0.02831797,
        -1.1879517 , -0.27915351],
       [-0.08274602,  0.72865883,  0.34437147, ..., -0.04992125,
         0.32398125, -0.73398843],
       [-0.51653687, -0.60359669, -0.39762465, ..., -0.1233724 ,
         0.22948544, -0.42000669]])

In [14]:
x_train_scaled, x_test_scaled = (scaler.transform(x_train), scaler.transform(x_test))

model = Lasso()
model_scaled = Lasso()

model.fit(x_train, y_train)
model_scaled.fit(x_train_scaled, y_train)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [15]:
print(model.score(x_test, y_test))
print(model_scaled.score(x_test_scaled, y_test))

0.8332155295449043
0.8332155298205985


#simplificar las transformaciones con transformaciones

In [18]:
model_scaled = make_pipeline(StandardScaler(), Lasso())
model_scaled.fit(x_train, y_train)
model_scaled.score(x_test, y_test)

0.8332155298205985

In [22]:
a = np.arange(6).reshape(3, 2)

transformer = PolynomialFeatures(2)
transformer.fit_transform(a)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [24]:
transformer = PolynomialFeatures(2)
transformer.fit_transform(x).shape

(4104, 45)

In [25]:
model_poly = make_pipeline(PolynomialFeatures(2), Lasso())
model_poly.fit(x_train, y_train)
model_poly.score(x_test, y_test)

0.8483387612214206