In [0]:
import torch
import numpy as np

import pandas as pd

#Trabajando con tensores

version de torch

In [0]:
torch.__version__

'1.4.0'

crear tensor con datos 1

In [0]:
tensor_a = torch.ones(2, 2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

crear tensor con datos aleatorios<br>
crear tensor con datos aleatorios entre dos numeros

In [0]:
tensor_b = torch.Tensor(2, 2)
print(tensor_b)
tensor_b.uniform_(0, 1)

tensor([[2.4651e-35, 0.0000e+00],
        [3.7835e-44, 0.0000e+00]])


tensor([[0.9334, 0.8200],
        [0.3107, 0.9563]])

tensor con numeros random

In [0]:
tensor_c = torch.rand(2, 2)
tensor_c

tensor([[0.9286, 0.7836],
        [0.8580, 0.8641]])

suma de tensores

In [0]:
result = tensor_b + tensor_c
result

tensor([[1.8620, 1.6036],
        [1.1686, 1.8205]])

shape => forma del tensor
view => cambiar tamaño tensor

In [0]:
print(tensor_a.shape)
reshaped = result.view(1, 4)
reshaped

torch.Size([2, 2])


tensor([[1.8620, 1.6036, 1.1686, 1.8205]])

crear tensor<br>
cambiar elemento de tensor<br>
array unidimensional

In [0]:
points = torch.tensor([[1.0, 2.0], [3.0,4.0]])
print(points)
points[0][1] = 2.5
print(points[0][1])
points.storage()

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


 1.0
 2.5
 3.0
 4.0
[torch.FloatStorage of size 4]

salto necesario para llegar al otro elemento en una dimension especifica

In [0]:
print(points.stride())

(2, 1)


transpuesta

In [0]:
p_t = points.t()
p_t

tensor([[1.0000, 3.0000],
        [2.5000, 4.0000]])

hacer un tensor con los elementos dados<br>
colocar todos los elementos en la misma dimension horizontal o vertical

In [0]:
tensor_x = torch.tensor([1,2,3,4])
print(torch.unsqueeze(tensor_x, 0))#horizontal
print(torch.unsqueeze(tensor_x, 1))#vertical

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


tensor con numpy y numeros random

In [0]:
numpyArray = np.random.rand(2, 2)
from_numpy = torch.from_numpy(numpyArray)
from_numpy

tensor([[0.5102, 0.0513],
        [0.7309, 0.4505]], dtype=torch.float64)

#Representar datos con tensores

---

media del tensor

In [0]:
print(from_numpy)
print(torch.mean(from_numpy))
print(torch.mean(from_numpy, dim=0))
print(torch.mean(from_numpy, dim=1))

tensor([[0.5102, 0.0513],
        [0.7309, 0.4505]], dtype=torch.float64)
tensor(0.4357, dtype=torch.float64)
tensor([0.6205, 0.2509], dtype=torch.float64)
tensor([0.2808, 0.5907], dtype=torch.float64)


desviacion estandar

In [0]:
torch.std(from_numpy, dim=1)

tensor([0.3245, 0.1982], dtype=torch.float64)

guardar tensor

In [0]:
torch.save(from_numpy, 'tensor.t')

cargar tensor

In [0]:
load = torch.load('tensor.t')
load

tensor([[0.5102, 0.0513],
        [0.7309, 0.4505]], dtype=torch.float64)

cargar dataset desde url

In [0]:
url = "https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv"
dataframe = pd.read_csv(url)
dataframe

mostrar columnas del dataset

In [0]:
dataframe.columns

hacer subconjunto del dataset- eliminar datos nulos

In [0]:
subset = dataframe[['Overall', 'Age', 'International Reputation', 'Weak Foot',
       'Skill Moves',]].dropna(axis=0, how='any')
columns = subset.columns[1:]
players = torch.tensor(subset.values).float()
players.shape, players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

tomar datos del subset

In [0]:
data = players[:, 1:]
data, data.shape

(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]), torch.Size([18159, 4]))

obtener primera columna (overall)

In [0]:
target = players[:, 0]
target, target.shape

(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

promedio datos

In [0]:
mean = torch.mean(data, dim=0)
mean

tensor([25.1225,  1.1132,  2.9473,  2.3613])

desviacion estandar de los datos

In [0]:
std = torch.std(data, dim=0)
std

tensor([4.6706, 0.3940, 0.6605, 0.7562])

normalizar datos

In [0]:
norm = (data - mean)/torch.sqrt(std)
norm

tensor([[ 2.7196,  6.1919,  1.2953,  1.8845],
        [ 3.6450,  6.1919,  1.2953,  3.0345],
        [ 0.4060,  6.1919,  2.5258,  3.0345],
        ...,
        [-4.2211, -0.1804,  0.0648, -0.4155],
        [-3.7584, -0.1804,  0.0648, -0.4155],
        [-4.2211, -0.1804,  0.0648, -0.4155]])

separar por edad<br>
torch.ge() valores mayores o iguales<br>
torch.gt() valores mayores<br>
torch.lt() valores menores<br>
torch.le() valores menores o iguales<br>

In [0]:
good = data[torch.ge(target, 85)]
average = data[torch.gt(target, 70) & torch.lt(target, 85)]
not_good = data[torch.le(target, 70)]

goodMean = torch.mean(good, dim=0)
averageMean = torch.mean(average, dim=0)
not_goodMean = torch.mean(not_good, dim=0)

for i, args in enumerate(zip(columns, goodMean, averageMean, not_goodMean)):
  print('{:25} {:6.2f} {:6.2f} {:6.2f}'.format(*args))

Age                        28.35  27.23  24.37
International Reputation    3.38   1.36   1.01
Weak Foot                   3.45   3.11   2.89
Skill Moves                 3.04   2.75   2.22
