In [1]:
import torch
import numpy as np

import pandas as pd

In [2]:
# Torch version
torch.__version__

'1.6.0+cu101'

In [3]:
# Create a tensor with only ones
tensor_a = torch.ones(2, 2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [4]:
# Create tensor with random numbers
tensor_b = torch.Tensor(2, 2)
print(tensor_b)
# Create tensor with random numbers between two numbers
tensor_b.uniform_(0, 1)

tensor([[2.6873e-36, 0.0000e+00],
        [3.7835e-44, 0.0000e+00]])


tensor([[0.2180, 0.0871],
        [0.9588, 0.3812]])

In [5]:
# Create tensor with random numbers
tensor_c = torch.rand(2, 2)
tensor_c

tensor([[0.5449, 0.9861],
        [0.6573, 0.8315]])

In [6]:
# Sum of tensors
result = tensor_b + tensor_c
result

tensor([[0.7629, 1.0732],
        [1.6161, 1.2127]])

In [7]:
# shape of tensor
print(tensor_a.shape)
# Reshape tensor
reshaped = result.view(1, 4)
reshaped

torch.Size([2, 2])


tensor([[0.7629, 1.0732, 1.6161, 1.2127]])

In [8]:
# Create tensor with values
points = torch.tensor([[1.0, 2.0], [3.0,4.0]])
# Change values of tensor
points[0][1] = 2.5
print(points[0][1])
# Form of storage tensor
points.storage()

tensor(2.5000)


 1.0
 2.5
 3.0
 4.0
[torch.FloatStorage of size 4]

In [9]:
# represents dense Tensors and is the memory layout that is most commonly used. Each strided tensor has an associated torch.Storage, which holds its data. These tensors provide multi-dimensional, strided view of a storage.
# bit jump needed to get to another element of the tensor
print(points.stride())

(2, 1)


In [10]:
# Transposed
p_t = points.t()
p_t

tensor([[1.0000, 3.0000],
        [2.5000, 4.0000]])

In [11]:
# Create a tensor with values
tensor_x = torch.tensor([1,2,3,4])
# Add dimension at the tensor
print(torch.unsqueeze(tensor_x, 0))#horizontal
print(torch.unsqueeze(tensor_x, 1))#vertical

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [12]:
# Create a tensor with numpy and random numbers
numpyArray = np.random.rand(2, 2)
from_numpy = torch.from_numpy(numpyArray)
from_numpy

tensor([[0.0925, 0.6483],
        [0.0606, 0.9527]], dtype=torch.float64)

# Represent data with tensors

---

In [13]:
print(from_numpy)
# Mean
print(torch.mean(from_numpy))
print(torch.mean(from_numpy, dim=0))
print(torch.mean(from_numpy, dim=1))

tensor([[0.0925, 0.6483],
        [0.0606, 0.9527]], dtype=torch.float64)
tensor(0.4385, dtype=torch.float64)
tensor([0.0765, 0.8005], dtype=torch.float64)
tensor([0.3704, 0.5066], dtype=torch.float64)


In [14]:
# Standard desviation
torch.std(from_numpy, dim=1)

tensor([0.3930, 0.6309], dtype=torch.float64)

In [15]:
# Save tensor
torch.save(from_numpy, 'tensor.t')

In [16]:
# Load tensor
load = torch.load('tensor.t')
load

tensor([[0.0925, 0.6483],
        [0.0606, 0.9527]], dtype=torch.float64)

In [17]:
# Load dataset from url
url = "https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv"
dataframe = pd.read_csv(url)
dataframe

Unnamed: 0      ID  ... GKReflexes  Release Clause
0               0  158023  ...        8.0         €226.5M
1               1   20801  ...       11.0         €127.1M
2               2  190871  ...       11.0         €228.1M
3               3  193080  ...       94.0         €138.6M
4               4  192985  ...       13.0         €196.4M
...           ...     ...  ...        ...             ...
18202       18202  238813  ...        9.0           €143K
18203       18203  243165  ...       12.0           €113K
18204       18204  241638  ...       13.0           €165K
18205       18205  246268  ...        9.0           €143K
18206       18206  246269  ...        9.0           €165K

[18207 rows x 89 columns]

In [18]:
# Show columns from dataset
dataframe.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [19]:
# Make a subset of the dataset and delete null data
subset = dataframe[['Overall', 'Age', 'International Reputation', 'Weak Foot',
       'Skill Moves',]].dropna(axis=0, how='any')
columns = subset.columns[1:]
players = torch.tensor(subset.values).float()
players.shape, players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [20]:
# Take data from the dataset
data = players[:, 1:]
data, data.shape

(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]), torch.Size([18159, 4]))

In [21]:
# Get the first column (overall)
target = players[:, 0]
target, target.shape

(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

In [22]:
# Mean of the data
mean = torch.mean(data, dim=0)
mean

tensor([25.1225,  1.1132,  2.9473,  2.3613])

In [23]:
# Standard desviation
std = torch.std(data, dim=0)
std

tensor([4.6706, 0.3940, 0.6605, 0.7562])

In [24]:
# Normalize data
norm = (data - mean)/torch.sqrt(std)
norm

tensor([[ 2.7196,  6.1919,  1.2953,  1.8845],
        [ 3.6450,  6.1919,  1.2953,  3.0345],
        [ 0.4060,  6.1919,  2.5258,  3.0345],
        ...,
        [-4.2211, -0.1804,  0.0648, -0.4155],
        [-3.7584, -0.1804,  0.0648, -0.4155],
        [-4.2211, -0.1804,  0.0648, -0.4155]])

separate for age  
torch.ge() greater or equals values  
torch.gt() greater values  
torch.lt() lower values
torch.le() lower or equal values

In [25]:
good = data[torch.ge(target, 85)]
average = data[torch.gt(target, 70) & torch.lt(target, 85)]
not_good = data[torch.le(target, 70)]

goodMean = torch.mean(good, dim=0)
averageMean = torch.mean(average, dim=0)
not_goodMean = torch.mean(not_good, dim=0)

for i, args in enumerate(zip(columns, goodMean, averageMean, not_goodMean)):
  print('{:25} {:6.2f} {:6.2f} {:6.2f}'.format(*args))

Age                        28.35  27.23  24.37
International Reputation    3.38   1.36   1.01
Weak Foot                   3.45   3.11   2.89
Skill Moves                 3.04   2.75   2.22
